### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by freddes51** [pierrdu/lmdi_gloss#5]
Hi,

When you put a key word in a definition it generates a crash (HTTP ERROR 500)
If you type a key words like that (Ponction lombaire, PL, ponctions lombaires, **ponction**) it crash because of keyword "ponction"

phpbb 3.3.8, 
lmdi_gloss 3.0.20
PHP Version 8.2.0RC5

**Error_log for the first problem**

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: PHP Fatal error:  Uncaught InvalidArgumentException: Cannot load XML: Extra content at the end of the document,

 [fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr:  in /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php:46,

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: Stack trace:,

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #0 /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderers/PHP.php(303): s9e\\TextFormatter\\Renderer->lo                                            adXML(), 
 [fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #1 /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php(66): s9e\\TextFormatter\\Renderers\\PHP->re                                            nderRichText(),

 [fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #2 /home/forumsep/public_html/phpbb/textformatter/s9e/renderer.php(250): s9e\\TextFormatter\\Renderer->render(),

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #3 /home/forumsep/public_html/includes/functions_content.php(600): phpbb\\textformatter\\s9e\\renderer->render(),

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #4 /home/forumsep/public_html/viewtopic.php(1763): generate_text_for_display(),

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr: #5 {main},

[fcgid:warn] [pid 582952:tid 139746440210176] [client 192.168.1.254:56825] mod_fcgid: stderr:   thrown in /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php on line 46,

Thank you for your help and your beautiful extension ;)

**Comment by pierrdu** [comment]
My test server is down for the time being. I seem to remember that keywords can't be composed. Ponction is fine, but ponction lombaire not, in part. when you use the tooltip feature. I'll come back.

**Comment by pierrdu** [comment]
My test server is now up again.
I checked with your keywords and I don't get any 500 error message.
Anyway, error 500 can have many causes. Do you have access thoe pache error log?

**Comment by freddes51** [comment]
Hi,
I have this problem on a phpbb test forum -> forumsep.freddes.com

Apache error logs when i put a keyword "SEP" in the definition of a term, and this keyword is used by another term in the glossary

https://forumsep.freddes.com/viewtopic.php?t=20433

[Sat Nov 26 15:31:02.379506 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: PHP Fatal error:  Uncaught InvalidArgumentException: Cannot load XML: Extra content at the end of the document, referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379527 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr:  in /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php:46, referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379531 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: Stack trace:, referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379540 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #0 /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderers/PHP.php(303): s9e\\TextFormatter\\Renderer->loadXML(), referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379543 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #1 /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php(66): s9e\\TextFormatter\\Renderers\\PHP->renderRichText(), referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379546 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #2 /home/forumsep/public_html/phpbb/textformatter/s9e/renderer.php(250): s9e\\TextFormatter\\Renderer->render(), referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379548 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #3 /home/forumsep/public_html/includes/functions_content.php(600): phpbb\\textformatter\\s9e\\renderer->render(), referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379551 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #4 /home/forumsep/public_html/viewtopic.php(1763): generate_text_for_display(), referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379554 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr: #5 {main}, referer: https://forumsep.freddes.com/viewforum.php?f=23
[Sat Nov 26 15:31:02.379556 2022] [fcgid:warn] [pid 582951:tid 139746440210176] [client 192.168.1.254:64725] mod_fcgid: stderr:   thrown in /home/forumsep/public_html/vendor/s9e/text-formatter/src/Renderer.php on line 46, referer: https://forumsep.freddes.com/viewforum.php?f=23

**Comment by pierrdu** [comment]
There is nothing about the glossary in this stack trace. What is this mod_fcgid, by the way?
